<a href="https://colab.research.google.com/github/hsrpedro006/hsrpedro006/blob/main/Aula1_fiap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 1

# Bibliotecas

In [ ]:
import pandas as pd
import numpy as np

# Exemplos Inicias

In [ ]:
# escalar
a = 1
a

1

In [ ]:
 # Lista
 lista_inicial = ['A', 2, True]
 lista_inicial

['A', 2, True]

In [ ]:
# Acessar Valores da lista
lista_inicial[1]

2

In [ ]:
# dicionario
dicionario_inicial = {'nomes': ['Luiz', 'Sara','Tiago'],
                    'RM' : [45, 678, 86198]}

In [ ]:
dicionario_inicial

{'nomes': ['Luiz', 'Sara', 'Tiago'], 'RM': [45, 678, 86198]}

In [ ]:
# acessar dicionario
dicionario_inicial['RM'][2]

86198

In [ ]:
dicionario_inicial['nomes'][0]

'Luiz'

In [ ]:
# DataFrame
dataframe_inicial = pd.DataFrame(dicionario_inicial)
dataframe_inicial

   nomes     RM
0   Luiz     45
1   Sara    678
2  Tiago  86198

In [ ]:
dataframe_inicial['RM']

0       45
1      678
2    86198
Name: RM, dtype: int64

In [ ]:
# Sempre um único tipo de dado
pd.DataFrame([1,2,"A"]).dtypes

0    object
dtype: object

In [ ]:
 scout_inicial = pd.read_csv('scouts_2015.csv')
 scout_inicial

,atleta_id,apelido,rodada_id,ano,clube_id,clube,posicao_id,posicao,jogos_num,pontos_num,...,FC,GC,CA,CV,SG,DD,DP,GS,status_id,status
0,87552,Vitor Bueno,27,2015,277,Santos,4,mei,1,0.0,...,0,0,0,0,0,0,0,0,0,NaN
1,87552,Vitor Bueno,28,2015,277,Santos,4,mei,1,0.0,...,0,0,0,0,0,0,0,0,0,NaN
2,87552,Vitor Bueno,29,2015,277,Santos,4,mei,1,0.0,...,0,0,0,0,0,0,0,0,0,NaN
3,87552,Vitor Bueno,30,2015,277,Santos,4,mei,1,0.0,...,0,0,0,0,0,0,0,0,0,NaN
4,87552,Vitor Bueno,31,2015,277,Santos,4,mei,2,-0.3,...,0,0,0,0,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29715,82943,Matheus Ribeiro,13,2015,293,Atlético-PR,2,lat,1,0.0,...,0,0,0,0,0,0,0,0,0,NaN
29716,82943,Matheus Ribeiro,14,2015,293,Atlético-PR,2,lat,1,0.0,...,0,0,0,0,0,0,0,0,0,NaN
29717,82943,Matheus Ribeiro,15,2015,293,Atlético-PR,2,lat,1,0.0,...,0,0,0,0,0,0,0,0,0,NaN
29718,86783,Henrique,6,2015,294,Coritiba,2,lat,2,-4.8,...,2,0,1,0,0,0,0,0,0,NaN
29719,86783,Henrique,7,2015,294,Coritiba,2,lat,3,-2.3,...,2,0,0,0,0,0,0,0,0,NaN

In [ ]:
scout_inicial.dtypes

atleta_id               int64
apelido                object
rodada_id               int64
ano                     int64
clube_id                int64
clube                  object
posicao_id              int64
posicao                object
jogos_num               int64
pontos_num            float64
media_num             float64
preco_num_anterior    float64
preco_num             float64
variacao_num          float64
FS                      int64
PE                      int64
A                       int64
FT                      int64
FD                      int64
FF                      int64
G                       int64
I                       int64
PP                      int64
RB                      int64
FC                      int64
GC                      int64
CA                      int64
CV                      int64
SG                      int64
DD                      int64
DP                      int64
GS                      int64
status_id               int64
status                float64
dtype: object

In [ ]:
scout_inicial[['apelido','clube']]

               apelido        clube
0          Vitor Bueno       Santos
1          Vitor Bueno       Santos
2          Vitor Bueno       Santos
3          Vitor Bueno       Santos
4          Vitor Bueno       Santos
...                ...          ...
29715  Matheus Ribeiro  Atlético-PR
29716  Matheus Ribeiro  Atlético-PR
29717  Matheus Ribeiro  Atlético-PR
29718         Henrique     Coritiba
29719         Henrique     Coritiba

[29720 rows x 2 columns]